FROM python:3.8.3
WORKDIR /app
ENV FLASK_APP=./backend/server.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD [ "flask", "run" ]
